# Generated by Django 3.2.1 on 2021-07-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name ', max_length=250)),
                ('last_name', models.CharField(help_text='Enter your last name ', max_length=250)),
                ('email', models.EmailField(help_text='Enter your email to receive product updates, discounts and promo', max_length=250)),
                ('local_address', models.CharField(help_text='Enter your local address', max_length=250)),
                ('state', models.CharField(help_text='Enter your state', max_length=250)),
            ],
        ),
    ]
